package za.ac.cput.domain;

public enum CollectionPoint {
    BELLVILLE_CAMPUS_LIBRARY,
    WELLINGTON_CAMPUS_LIBRARY,
    DISTRICT_SIX_CAMPUS_LIBRARY,
    MOWBRAY_CAMPUS_LIBRARY,
    GRANGER_BAY_CAMPUS_LIBRARY,
    CAPE_TOWN_CAMPUS_LIBRARY,
    WORCESTER_CAMPUS_LIBRARY
}
